company_name: "Acme Widgets, Inc."
company_url: "https://www.knowmad.com"
contact_email:
    - cromedome@gmail.com
    - william@knowmad.com
company_logo: "images/Acme-corp.png"

# For tailwind UI, consider making bg 400 grey and fg 800 blue
brand_color: "#cccccc"
page_title: "Leave a Review"
page_description: "Help us. Help others. This is your invitation to review."

review_sites:
    -
        site: Google
        url: http://search.google.com/local/writereview?placeid=ChIJQ4I-lBygVogRMPJCWKo4POU
    -
        site: Facebook
        url: http://www.facebook.com/110980017714
    -
        site: Yelp
        url: xxx
    -
        site: Upcity
        url: https://upcity.com/local-marketing-agencies/profiles/knowmad#review
        logo: /images/logos/upcity-logo.png

sendgrid:
    api_key: your_key_goes_here
    from: 'noreply@collectivevoice.com'
